In [2]:
import numpy as np

In [ ]:
#numpy 배열생성
a=[1,2,3,4,5] #파이썬 리스트
b=np.array(a) #넘파이 리스트 -> ,가 없음
c=np.array([1,3,5])
print(a)
print(b)
print(c)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1 3 5]


In [ ]:
#넘파이 배열 복제
a=np.array([1,2,3,4,5])
b=a
c=a.copy() # 새로운 객체 생성

b[0]=99
print(a)
print(b) # 원본을 수정해도 같이 수정됨
print(c) # 새로운 객체 생성

[99  2  3  4  5]
[99  2  3  4  5]
[1 2 3 4 5]


In [ ]:
print(b[2])
print(a[2])
print(c[-1])
print(c[0:2])

3
3
5
[1 2]


In [ ]:
#넘파이 배열 호출
a = [1, 2, 3, 4, 5]
b = np.array(a)
c = np.array([1, 3, 5])

#넘파이 배열 계산
print(a*2) # 파이썬 리스트에 * n = n번 반복
print(b*2) # 값들을 2배씩 곱함
print(c+3) # 값마다 3씩 더함

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[4 6 8]


In [ ]:
#1차원 배열
a = np.array([1,2,3],dtype=int)
b = np.array([1.1,2.2,3.3],dtype=float)
a1 = np.array([1,2,3],dtype=float)
c = np.array([1,1,0],dtype=bool)

print(a)
print(b)
print(a1)
print(c)

[1 2 3]
[1.1 2.2 3.3]
[1. 2. 3.]
[ True  True False]


In [ ]:
#true false
print(np.array(([-1,-3,1,0,5,7]),dtype=bool))

[ True  True  True False  True  True]


In [ ]:
#다차원 배열
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(b)
print(b[0][1][1])

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
4


In [ ]:
#배열 속성 반환
print(b.ndim) # 차원
print(b.shape) # 1차원 3개, 2차원 2개, 2차원 2개
print(b.dtype) # 64비트

3
(3, 2, 2)
int64


In [ ]:
#모든 값이 1인 배열_ 초기화
a = np.ones((2,2),dtype=int)
b = [1,2,3,4,5]
c = np.ones_like(b,dtype=int) # b의 크기와 동일하고 모든 원소의 값이 1인 배열

print(a)
print(b)
print(c)

[[1 1]
 [1 1]]
[1, 2, 3, 4, 5]
[1 1 1 1 1]


In [ ]:
#모든 값이 0인 배열
a = np.zeros((2,2),dtype=int)
b = [1,2,3,4,5]
c = np.zeros_like(b,dtype=int)

print(a)
print(b)
print(c)

[[0 0]
 [0 0]]
[1, 2, 3, 4, 5]
[0 0 0 0 0]


In [ ]:
# 모든 값이 비어있는 배열
a = np.empty((2,2),dtype=int)
b = [1,2,3,4,5]
c = np.empty_like(b,dtype=int)

print(a)
print(b)
print(c)

[[0 0]
 [0 0]]
[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
#  대각의 값이 1인 배열(단위 행렬)
a = np.identity(4,dtype=int) # 4*4의 단위행렬
b = np.eye(4,4,k=1,dtype=int) # k값만큼 이격된 단위 행렬

print(a)
print(b)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [ ]:
a = np.identity(20,dtype=int)
b = np.eye(7,7,k=2,dtype=int)
c = np.eye(7,7,k=-2,dtype=int) 

print(a)
print('\n\n')
print(b)
print('\n\n')
print(c)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]



[[0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]



[[0 0 0 0 0 0

In [ ]:
#등간격
a = np.arange(0,10,step=5)
b = np.arange(1,10,step=5)
c = np.arange(0,10,step=1)
print(a)
print(b)
print(c)

[0 5]
[1 6]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a = np.linspace(0,10,num=5,endpoint=True,retstep=True) # 0부터 10 사이의 값을 num만큼 생성하여 배열로 반환 / retstep이 true일 경우 값들의 간격을 표히새줌
b = np.linspace(1,10,num=5,endpoint=True,retstep=False) # 1부터 10까지를 5등분
c = np.linspace(0,10,num=5,endpoint=False,retstep=False) # endpoint가 ture일 경우 end의 값이 마지막이 됨
print(a)
print(b)
print(c)

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)
[ 1.    3.25  5.5   7.75 10.  ]
[0. 2. 4. 6. 8.]


In [ ]:
#로그 배율을 사용
a = np.logspace(0,10,num=5,endpoint=True,base=10.0)
b = np.logspace(1,10,num=5,endpoint=True,base=5.0)
c = np.logspace(0,10,num=5,endpoint=False,base=1.0)
print(a)
print(b)
print(c)

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]
[5.00000000e+00 1.86918598e+02 6.98771243e+03 2.61226682e+05
 9.76562500e+06]
[1. 1. 1. 1. 1.]


In [ ]:
a = np.array([1,2,3,4,5])
print(a)
print('\n')
print(a[3:])
print('\n')
print(a[1:-1])
print('\n')
print(a[0:3:2])

[1 2 3 4 5]


[4 5]


[2 3 4]


[1 3]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('\n')
print(a[:,1:]) # 모든행 / 각 열의 인덱스 1부터 끝까지
print('\n')
print(a[0:1,0:2]) # 첫행 / 인덱스 0부터 인덱스 2까지

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[2 3]
 [5 6]
 [8 9]]


[[1 2]]


In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a)
print('\n')
print(a[::2,::2]) # 모든 행을 2간격만큼 / 모든 열을 2간격만큼

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


[[ 1  3  5]
 [11 13 15]]


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print('\n')
print(np.shape(a))
a.shape=(6,2)
print('\n')
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(3, 4)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]) # 3차원 배열
print(a)
print('\n')
print(np.shape(a)) # 페이지, 행, 열
print('\n')
a.shape = (2, 3, 3) # 총 길이(곱)과 같아야 함.
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


(3, 2, 3)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [3]:
np.random.seed(76923)

a = np.random.rand(2, 2)
b = np.random.randn(2, 2)
c = np.random.randint(1, 3, (2, 2), dtype=int)

print(a)
print(b)
print(c)

[[0.76367992 0.87641303]
 [0.53095238 0.38451373]]
[[-0.15929049 -0.07981017]
 [ 1.73777738 -0.47496771]]
[[1 1]
 [2 1]]
